import React, { createContext, useContext, useState, useCallback, useEffect } from 'react'

export const translations = {
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.pricing': 'Apóyanos',
    'nav.faq': 'FAQ',
    'nav.study': 'Estudiar',
    'nav.login': 'Entrar',
    'nav.support': 'Apóyanos',
    'nav.contact': 'Contacto',
    'lang.toggle': 'EN',
    // Home
    'hero.badge': 'Potenciado por IA',
    'hero.title.1': 'Convierte tus apuntes en',
    'hero.title.2': 'flashcards',
    'hero.title.3': 'que de verdad recuerdas',
    'hero.subtitle':
      'Pega tus notas y deja que la IA cree tarjetas de estudio listas para repasar. Gratis y en segundos.',
    'how.title': 'Cómo funciona',
    'how.step1': 'Pega tus apuntes',
    'how.step1.desc': 'Copia el texto o sube un PDF, TXT o DOCX. Sin límite de temas.',
    'how.step2': 'La IA crea las tarjetas',
    'how.step2.desc': 'En segundos convierte tus notas en preguntas y respuestas claras.',
    'how.step3': 'Estudia de verdad',
    'how.step3.desc': 'Repasa con modos básico, contra reloj o repetición espaciada.',
    'feat.title': 'Todo lo que necesitas',
    'feat.f1': 'IA que entiende',
    'feat.f1.desc': 'No copia y pega: genera preguntas que de verdad te hacen pensar.',
    'feat.f2': 'Repetición espaciada',
    'feat.f2.desc': 'Estudia menos tiempo recordando más, con el método científico.',
    'feat.f3': 'Tus formatos',
    'feat.f3.desc': 'PDF, DOCX o texto plano. Suelta el archivo y listo.',
    'feat.f4': 'Gratis para siempre',
    'feat.f4.desc': 'StudySpark es 100% gratis. Sin sorpresas.',
    'testi.title': 'Lo que dicen los estudiantes',
    'cta.title': 'Empieza a estudiar mejor hoy',
    'cta.subtitle': 'Gratis para empezar. Sin tarjeta. Sin compromisos.',
    'cta.button': 'Crear mis flashcards',
    // Support page (replaces pricing)
    'support.title': 'Apoya StudySpark',
    'support.subtitle': 'StudySpark es gratis y de código abierto. Si te ayuda, invítame un café ☕',
    'support.kofi': 'Apóyanos en Ko-fi',
    'support.thanks': '¡Gracias por tu apoyo! Tu donación mantiene el proyecto vivo y gratuito para todos.',
    'support.f1': 'Servidores y hosting',
    'support.f2': 'Desarrollo de nuevas funciones',
    'support.f3': 'Mantenimiento y mejoras',
    'support.f4': 'Mantenerlo gratis para todos',
    'support.whatFunds': '¿En qué se invierte tu apoyo?',
    'support.tiers': 'Cualquier aporte cuenta',
    'support.heart': 'Hecho con cariño para estudiantes',
    // FAQ
    'faq.title': 'Preguntas frecuentes',
    'faq.subtitle': 'Todo lo que necesitas saber antes de empezar.',
    'faq.q1': '¿Es gratis StudySpark?',
    'faq.a1': 'Sí, totalmente. StudySpark es gratuito y de código abierto. Sin límites de tarjetas, sin suscripciones.',
    'faq.q2': '¿Qué formatos de archivo acepta?',
    'faq.a2': 'Puedes pegar texto directamente o subir archivos TXT, PDF y DOCX. La IA extrae el contenido y crea las tarjetas.',
    'faq.q3': '¿Mis apuntes están seguros?',
    'faq.a3': 'Tus apuntes se usan únicamente para generar tus flashcards en el momento. No los compartimos ni vendemos.',
    'faq.q4': '¿Cómo funciona la repetición espaciada?',
    'faq.a4': 'Es un método de estudio que muestra cada tarjeta justo antes de que la olvides, optimizando cuánto recuerdas con menos tiempo.',
    'faq.q5': '¿Puedo exportar mis tarjetas?',
    'faq.a5': 'Sí. Puedes descargarlas en CSV o JSON para usarlas en otras apps.',
    // Study
    'study.empty.title': 'No hay sesión de estudio activa',
    'study.empty.desc': 'Aún no has generado flashcards con IA. Sube tus apuntes o pega tu texto para crear un mazo y empezar a repasar.',
    'study.empty.cta': 'Subir apuntes y crear mazo',
    'study.empty.library': 'Abrir biblioteca',
    'study.demo': 'Probar mazo de demostración',
    'study.back': 'Volver al inicio',
    'study.card': 'Tarjeta',
    'study.of': 'de',
    'study.show': 'Mostrar respuesta',
    'study.prev': 'Anterior',
    'study.next': 'Siguiente',
    'study.restart': 'Reiniciar',
    'study.correct': 'Correcto',
    'study.wrong': 'Incorrecto',
    'study.hide': 'Ocultar',
    'study.wasit': '¿Esta respuesta fue correcta?',
    'study.answered.correct': '¡Correcto!',
    'study.answered.wrong': 'No del todo',
    'study.time': 'Tiempo',
    'study.known': 'Lo sé',
    'study.again': 'Repetir',
    'study.copy': 'Copiar',
    'study.copied': '¡Copiado!',
    'study.speak': 'Escuchar',
    'study.progress': 'Progreso',
    'study.flip.hint': 'Pulsa la tarjeta o la barra espaciadora para ver la respuesta',
    'study.pause': 'Pausar',
    'study.resume': 'Reanudar',
    'study.paused': 'Pausado',
    'study.known.label': 'Dominado',
    'study.again.label': 'Por repasar',
    // Auth
    'auth.login': 'Inicia sesión',
    'auth.register': 'Crea tu cuenta',
    'auth.login.desc': 'Accede a tus flashcards',
    'auth.register.desc': 'Empieza a estudiar gratis',
    'auth.name': 'Nombre (opcional)',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.enter': 'Entrar',
    'auth.create': 'Crear cuenta',
    'auth.noaccount': '¿No tienes cuenta?',
    'auth.hasaccount': '¿Ya tienes cuenta?',
    'auth.toregister': 'Regístrate',
    'auth.tologin': 'Inicia sesión',
    'auth.avatar': 'Tu avatar',
    'auth.avatar.hint': 'Elige un avatar geométrico. Se guarda en tu cuenta y puedes cambiarlo luego.',
    'auth.avatar.random': 'Aleatorio',
    'auth.avatar.shapes': 'Formas',
    'auth.avatar.ring': 'Anillos',
    'auth.avatar.bauhaus': 'Bauhaus',
    // 404
    'notfound.title': 'Página no encontrada',
    'notfound.desc': 'La página que buscas no existe o se ha movido. Volvamos al camino correcto.',
    'notfound.home': 'Ir al inicio',
    // Footer
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.contact': 'Contacto',
    'footer.copy': 'Hecho con IA para estudiantes.',
    // Auth - confirmación de email
    'auth.checkmail': 'Revisa tu correo',
    'auth.checkmail.desc': 'Te hemos enviado un enlace de confirmación a',
    'auth.checkmail.resend': 'Reenviar correo',
    'auth.checkmail.resending': 'Enviando...',
    'auth.checkmail.sent': '¡Correo reenviado!',
    'auth.checkmail.open': 'Abrir correo',
    'auth.checkmail.note': 'Haz clic en el enlace para activar tu cuenta. La sesión se iniciará sola.',
    'auth.confirmed': '¡Cuenta confirmada!',
    'auth.confirmed.desc': 'Tu sesión se ha iniciado automáticamente.',
    'auth.confirm.error': 'No se pudo confirmar la cuenta. El enlace puede haber caducado.',
    'auth.backto.login': 'Volver a iniciar sesión',
    // Perfil / dropdown
    'profile.menu': 'Mi cuenta',
    'profile.sessions': 'Mis sesiones',
    'profile.recentsessions': 'Sesiones recientes',
    'profile.settings': 'Ajustes',
    'profile.logout': 'Cerrar sesión',
    'profile.free': 'Gratis',
    'profile.xp': 'XP',
    'profile.streak': 'Racha',
    'profile.days': 'días',
    'profile.nosessions': 'Aún no tienes sesiones guardadas',
    'profile.opensession': 'Abrir sesión',
    'profile.back': 'Volver',
    // Library (folders / storage)
    'library.title': 'Mi biblioteca',
    'library.subtitle': 'Organiza tus mazos en carpetas. Arrastra un mazo sobre una carpeta para moverlo.',
    'library.filter': 'Filtrar mazos...',
    'library.newfolder': 'Nueva carpeta',
    'library.foldername': 'Nombre de la carpeta',
    'library.uncategorized': 'Sin carpeta',
    'library.all': 'Todos los mazos',
    'library.rename': 'Renombrar',
    'library.delete': 'Eliminar',
    'library.move': 'Mover a...',
    'library.moved.to': 'Movido a {folder}',
    'library.study': 'Estudiar',
    'library.empty': 'Todavía no tienes mazos guardados.',
    'library.folder.empty': 'Esta carpeta está vacía.',
    'library.confirm.delete.folder': '¿Eliminar la carpeta? Los mazos dentro volverán a "Sin carpeta".',
    'library.confirm.delete.session': '¿Eliminar este mazo? Esta acción no se puede deshacer.',
    'library.rename.session': 'Renombrar mazo',
    'library.session.name': 'Nombre del mazo',
    'library.cards': 'tarjetas',
    'library.open': 'Abrir',
    'library.color': 'Color',
    'library.color.none': 'Sin color',
    'library.export.csv': 'Exportar CSV',
    'library.newfolder.here': 'Nueva carpeta',
    'library.created': 'Carpeta creada',
    'library.renamed': 'Carpeta renombrada',
    'library.save': 'Guardar',
    'library.last': 'Última vez',
    'library.never': 'Sin repasar',
    'library.style': 'Estilo',
    'library.move.short': 'Mover',
    'library.delete.withcontents': 'Eliminar con contenido',
    'library.confirm.delete.folder.plain': '¿Eliminar la carpeta? Su contenido quedará en este mismo sitio.',
    'library.confirm.delete.folder.contents': '¿Eliminar DEFINITIVAMENTE la carpeta y TODO su contenido? Esta acción no se puede deshacer.',
    // Recompensas
    'reward.title': '¡Sesión completada!',
    'reward.subtitle': 'Has repasado',
    'reward.cards': 'tarjetas',
    'reward.known': 'dominadas',
    'reward.time': 'Tiempo',
    'reward.accuracy': 'Acierto',
    'reward.xp': '+{amount} XP ganados',
    'reward.xp.already': 'XP ya conseguida',
    'reward.save.title': 'Guardar este mazo',
    'reward.save.cta': 'Guardar',
    'reward.save.folder': 'Carpeta',
    'reward.saved': 'Mazo guardado en tu biblioteca',
    'reward.discard': 'Desechar',
    'reward.discarded': 'Mazo descartado',
    'reward.discard.warn': 'El mazo actual se descartará y no se guardará. ¿Continuar?',
    'reward.upload.another': 'Subir otro archivo',
    'reward.streak': '¡Racha de {days} días!',
    'reward.streak.best': 'Tu mejor racha',
    'reward.review': 'Repasar de nuevo',
    'reward.home': 'Volver al inicio',
    'reward.level': 'Nivel {level}',
    'reward.correct.list': 'Acertaste',
    'reward.wrong.list': 'Fallaste',
    'reward.show.wrong': 'Ver las que fallé',
    'reward.hide.wrong': 'Ocultar',
    'reward.retry.wrong': 'Repasar solo las falladas',
    'reward.finish': 'Terminar sesión',
    'reward.summary': 'Resumen de la sesión',
    'reward.unanswered': 'Sin responder: {count}',
    'study.end': 'Terminar',
    'study.review.wrong': 'Repasar falladas',
    'study.unanswered.warn': 'Aún quedan {count} sin responder',
    'export.title': 'Exportar sesiones',
    'export.desc': 'Descárgate todas tus tarjetas para usarlas donde quieras.',
    'export.csv': 'Exportar CSV',
    'export.json': 'Exportar JSON',
    'export.single': 'Exportar este mazo',
    'export.done': 'Sesiones exportadas',
    'export.one': 'Mazo exportado',
    'filename.label': 'Nombre del archivo (opcional)',
    'filename.placeholder': 'Ej: Tema 3 - Fotosíntesis',
    'cta.bottom': '¿Listo para empezar? Crea tus flashcards',
    'cta.create': 'Crear mis flashcards',
    // Chatbot
    'chatbot.title': 'Mara · Asistente',
    'chatbot.placeholder': 'Escríbeme o toca una sugerencia...',
    'chatbot.welcome': '¡Hola! Soy Mara, tu asistente en StudySpark 😊 Cuéntame, ¿vas a crear un mazo nuevo o estás repasando? Estoy aquí para lo que necesites.',
    'chatbot.help': 'En línea y encantada de ayudar',
    'chatbot.back': 'Volver a los temas',
    'chatbot.unknown': 'Mmm, eso se me escapa un poquito 🤔 Prueba a preguntarme sobre: crear tarjetas, modos de estudio, exportar tus mazos, tu cuenta, o cómo apoyarnos. ¿Por dónde quieres que empecemos?',
    'chatbot.topics.create': '¡Buena idea! Ve a Inicio, pega tus apuntes o sube un archivo (PDF, TXT o DOCX) y pulsa "Generar". En segundos la IA convierte tus notas en preguntas y respuestas, e incluso marca la dificultad de cada una. Cuando estén listas, elige cómo quieres repasarlas y ¡a estudiar! 🚀',
    'chatbot.topics.study': 'Tenemos 3 modos para todos los gustos: Básico (a tu ritmo, sin prisas), Contrarreloj (30s fijos por tarjeta, te entrena a pensar rápido) y Repetición Espaciada (la IA repite cada tarjeta justo antes de que la olvides). Los eliges en el botón de ajustes ⚙️ antes de empezar. ¿Cuál prefieres probar?',
    'chatbot.topics.export': 'Claro que sí. Al terminar una sesión verás botones para exportar a CSV o JSON, y desde Ajustes > Mis datos puedes bajar todas tus sesiones de golpe. Así tus tarjetas viajan contigo a donde quieras. 📤',
    'chatbot.topics.account': 'Crea tu cuenta con tu email y tu progreso, racha y puntos se guardan automáticamente. Abres sesión en cualquier dispositivo y te encuentras todo tal como lo dejaste. 🔐',
    'chatbot.topics.donate': 'StudySpark es gratis y de código abierto, y quiero que siga siéndolo para siempre ☕ Si te resulta útil y quieres invitarme a un café, aquí tienes mi Ko-fi: https://ko-fi.com/mvalera_dev. Pero ojo: nunca es obligatorio, todos los modos son gratis igualmente. ¡Gracias de corazón! ❤️',
    // Upload area
    'upload.title': 'Sube tus apuntes',
    'upload.cardcount.note': 'predeterminado',
    'upload.cardcount.auto': 'Dejar que la IA decida',
    'upload.drag': 'Arrastra y suelta tu archivo',
    'upload.click': 'o haz clic para buscar',
    'upload.formats': 'PDF, TXT, DOCX (máx. 10MB)',
    'upload.drop': 'Suelta el archivo aquí',
    'upload.text.label': 'Pega tus apuntes directamente:',
    'upload.text.placeholder': 'Pega aquí el texto de tus apuntes...',
    'upload.or': 'O',
    'upload.clear': 'Limpiar',
    'upload.fromtext': 'Generar desde texto',
    'upload.fromfile': 'Generar desde archivo',
    'upload.processing': 'Procesando tus apuntes...',
    'upload.processing.sub': 'La IA está creando tus flashcards',
    'upload.preview': 'Vista previa:',
    // Loading screen (async generation)
    'loading.title': 'Generando tus flashcards',
    'loading.step.reading': 'Leyendo tu documento...',
    'loading.step.thinking': 'La IA está estudiando el contenido...',
    'loading.step.writing': 'Redactando las flashcards...',
    'loading.step.almost': 'Casi listo, dando los últimos retoques...',
    'loading.hint': 'Esto puede tardar hasta un par de minutos. No cierres esta página.',
    'loading.timeout': 'La generación está tardando demasiado. Inténtalo de nuevo.',
    // Flashcard
    'card.question': 'Pregunta',
    'card.answer': 'Respuesta',
    'card.copy': 'Copiar',
    'card.copied': '¡Copiado!',
    'card.listen': 'Escuchar',
    'card.stop': 'Parar',
    'card.flip.hint.short': 'Pulsa la tarjeta para voltear',
    'card.very-easy': 'Muy fácil',
    'card.easy': 'Fácil',
    'card.medium': 'Media',
    'card.hard': 'Difícil',
    'card.very-hard': 'Muy difícil',
    'card.no.difficulty': 'Sin nivel',
    'card.time.up': '¡Tiempo!',
    // Study modes
    'mode.basic': 'Básico',
    'mode.timed': 'Contrarreloj',
    'mode.spaced': 'Repetición espaciada',
    'mode.basic.desc': 'Estudia a tu ritmo, sin prisas.',
    'mode.timed.desc': 'Responde antes de que se acabe el tiempo.',
    'mode.spaced.desc': 'La IA repite cada tarjeta justo antes de que la olvides.',
    'mode.recording': 'Grabando',
    'mode.paused': 'En pausa',
    // Session config
    'config.title': 'Configura tu sesión',
    'config.subtitle': 'Elige cómo quieres repasar este mazo.',
    'config.mode': 'Modo de estudio',
    'config.order': 'Orden de las tarjetas',
    'config.order.default': 'Tal cual (orden original)',
    'config.order.shuffle': 'Barajadas al azar',
    'config.order.hard': 'Difíciles primero',
    'config.direction': 'Dirección',
    'config.direction.qa': 'Pregunta → Respuesta',
    'config.direction.aq': 'Respuesta → Pregunta',
    'config.autoplay': 'Leer en voz alta al voltear',
    'config.start': 'Empezar a estudiar',
    'config.cancel': 'Cancelar',
    // Settings
    'settings.title': 'Ajustes',
    'settings.subtitle': 'Personaliza tu experiencia de estudio.',
    'settings.language': 'Idioma',
    'settings.lang.es': 'Español',
    'settings.lang.en': 'English',
    'settings.studyprefs': 'Preferencias de estudio',
    'settings.defaultmode': 'Modo por defecto',
    'settings.cardcount': 'Flashcards por mazo',
    'settings.cardcount.max': 'máximo',
    'settings.speak': 'Leer tarjetas en voz alta',
    'settings.speak.desc': 'Reproduce el texto automáticamente al voltear cada tarjeta.',
    'settings.autoplay': 'Reproducción automática',
    'settings.autoplay.desc': 'Activa la lectura por voz por defecto en nuevas sesiones.',
    'settings.data': 'Mis datos',
    'settings.export': 'Exportar mis sesiones',
    'settings.export.desc': 'Descarga todas tus tarjetas en CSV para usarlas donde quieras.',
    'settings.delete': 'Borrar mi progreso',
    'settings.delete.desc': 'Elimina las sesiones guardadas de este dispositivo.',
    'settings.delete.confirm': '¿Borrar todo el progreso local? Esta acción no se puede deshacer.',
    'settings.deleted': 'Progreso borrado',
    'settings.saved': 'Preferencias guardadas',
    'settings.account': 'Cuenta',
    'settings.plan': 'Plan',
    'settings.avatar': 'Tu avatar',
    'settings.avatar.desc': 'Avatar geométrico de tu perfil',
    'settings.avatar.saved': 'Avatar actualizado',
    // FAQ
    'faq.search': 'Buscar en las preguntas...',
    'faq.noresults': 'No encontramos preguntas para tu búsqueda.',
    'faq.cat.all': 'Todos',
    'faq.cat.general': 'General',
    'faq.cat.files': 'Archivos y formatos',
    'faq.cat.study': 'Estudio y modos',
    'faq.help.title': '¿Sigues con dudas?',
    'faq.help.desc': 'Escríbenos y te ayudamos en menos de 24h.',
    'faq.help.button': 'Contactar',
    'faq.q6': '¿Puedo usar StudySpark en el móvil?',
    'faq.a6': 'Sí. StudySpark es una web responsive: se adapta a tu móvil y tableta sin instalar nada. Solo necesitas un navegador.',
    'faq.q7': '¿Qué es el modo contrarreloj?',
    'faq.a7': 'Cada tarjeta tiene 30 segundos para responder. Te entrena para pensar rápido bajo presión.',
    'faq.q8': '¿Puedo exportar mis tarjetas?',
    'faq.a8': 'Sí, al terminar una sesión verás botones para exportar a CSV o JSON. También desde Ajustes > Mis datos.',
    'faq.q9': '¿Qué pasa si pierdo mi racha?',
    'faq.a9': 'Si un día no estudias, la racha vuelve a 1. Pero puedes recuperarla estudiando al día siguiente. ¡Tu XP acumulado se queda!',
    'faq.q10': '¿Cómo contacto con vosotros?',
    'faq.a10': 'Puedes usar el botón de contacto en la cabecera o escribir a hola@studyspark.pp.ua. Respondemos en menos de 24h.',
    'faq.cat.support': 'Apoyo',
    // Contact page
    'contact.title': 'Contacta con nosotros',
    'contact.subtitle': '¿Tienes dudas, sugerencias o solo quieres saludar? Escríbenos y te responderemos en menos de 24h.',
    'contact.name': 'Nombre',
    'contact.email': 'Email',
    'contact.subject': 'Asunto',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar',
    'contact.sending': 'Enviando...',
    'contact.sent': '¡Mensaje enviado!',
    'contact.success.title': '¡Mensaje enviado!',
    'contact.success.desc': 'Gracias por contactarnos. Te responderemos lo antes posible.',
    'contact.another': 'Enviar otro mensaje',
    'contact.home': 'Volver al inicio',
    'contact.privacy': 'Al enviar aceptas nuestra política de privacidad.',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.support': 'Support Us',
    'nav.faq': 'FAQ',
    'nav.study': 'Study',
    'nav.login': 'Log in',
    'nav.contact': 'Contact',
    'lang.toggle': 'ES',
    // Home
    'hero.badge': 'Powered by AI',
    'hero.title.1': 'Turn your notes into',
    'hero.title.2': 'flashcards',
    'hero.title.3': 'you actually remember',
    'hero.subtitle':
      'Paste your notes and let AI create study cards ready to review. Free and in seconds.',
    'how.title': 'How it works',
    'how.step1': 'Paste your notes',
    'how.step1.desc': 'Copy text or upload a PDF, TXT or DOCX. No topic limit.',
    'how.step2': 'AI creates the cards',
    'how.step2.desc': 'In seconds it turns your notes into clear questions and answers.',
    'how.step3': 'Study for real',
    'how.step3.desc': 'Review with basic, timed or spaced-repetition modes.',
    'feat.title': 'Everything you need',
    'feat.f1': 'AI that understands',
    'feat.f1.desc': 'It does not copy-paste: it writes questions that make you think.',
    'feat.f2': 'Spaced repetition',
    'feat.f2.desc': 'Study less time while remembering more, with the scientific method.',
    'feat.f3': 'Your formats',
    'feat.f3.desc': 'PDF, DOCX or plain text. Drop the file and done.',
    'feat.f4': 'Free forever',
    'feat.f4.desc': 'StudySpark is 100% free. No surprises.',
    'testi.title': 'What students say',
    'cta.title': 'Start studying better today',
    'cta.subtitle': 'Free to start. No card. No commitment.',
    'cta.button': 'Create my flashcards',
    // Support page (replaces pricing)
    'support.title': 'Support StudySpark',
    'support.subtitle': 'StudySpark is free and open source. If it helps you, buy me a coffee ☕',
    'support.kofi': 'Support us on Ko-fi',
    'support.thanks': 'Thanks for your support! Your donation keeps the project alive and free for everyone.',
    'support.f1': 'Servers and hosting',
    'support.f2': 'New feature development',
    'support.f3': 'Maintenance and improvements',
    'support.f4': 'Keep it free for everyone',
    'support.whatFunds': 'Where your support goes',
    'support.tiers': 'Every little bit helps',
    'support.heart': 'Made with love for students',
    // FAQ
    'faq.title': 'Frequently asked questions',
    'faq.subtitle': 'Everything you need to know before starting.',
    'faq.q1': 'Is StudySpark free?',
    'faq.a1': 'Yes, completely. StudySpark is free and open source. No card limits, no subscriptions.',
    'faq.q2': 'What file formats does it accept?',
    'faq.a2': 'You can paste text directly or upload TXT, PDF and DOCX files. The AI extracts content and builds the cards.',
    'faq.q3': 'Are my notes safe?',
    'faq.a3': 'Your notes are only used to generate your flashcards in the moment. We do not share or sell them.',
    'faq.q4': 'How does spaced repetition work?',
    'faq.a4': 'It is a study method that shows each card just before you forget it, optimizing how much you remember with less time.',
    'faq.q5': 'Can I export my cards?',
    'faq.a5': 'Yes. You can download them as CSV or JSON to use in other apps.',
    // Study
    'study.empty.title': 'No active study session',
    'study.empty.desc': 'You have not generated flashcards with AI yet. Upload your notes or paste your text to build a deck and start reviewing.',
    'study.empty.cta': 'Upload notes & create a deck',
    'study.empty.library': 'Open library',
    'study.demo': 'Try demo deck',
    'study.back': 'Back to home',
    'study.card': 'Card',
    'study.of': 'of',
    'study.show': 'Show answer',
    'study.prev': 'Previous',
    'study.next': 'Next',
    'study.restart': 'Restart',
    'study.correct': 'Correct',
    'study.wrong': 'Wrong',
    'study.hide': 'Hide',
    'study.wasit': 'Was this answer correct?',
    'study.answered.correct': 'Correct!',
    'study.answered.wrong': 'Not quite',
    'study.time': 'Time',
    'study.known': 'I know it',
    'study.again': 'Repeat',
    'study.copy': 'Copy',
    'study.copied': 'Copied!',
    'study.speak': 'Listen',
    'study.progress': 'Progress',
    'study.flip.hint': 'Tap the card or press space to reveal the answer',
    'study.pause': 'Pause',
    'study.resume': 'Resume',
    'study.paused': 'Paused',
    'study.known.label': 'Mastered',
    'study.again.label': 'To review',
    // Auth
    'auth.login': 'Log in',
    'auth.register': 'Create account',
    'auth.login.desc': 'Access your flashcards',
    'auth.register.desc': 'Start studying for free',
    'auth.name': 'Name (optional)',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enter': 'Enter',
    'auth.create': 'Create account',
    'auth.noaccount': "Don't have an account?",
    'auth.hasaccount': 'Already have an account?',
    'auth.toregister': 'Sign up',
    'auth.tologin': 'Log in',
    'auth.avatar': 'Your avatar',
    'auth.avatar.hint': 'Pick a geometric avatar. It is saved to your account and you can change it later.',
    'auth.avatar.random': 'Random',
    'auth.avatar.shapes': 'Shapes',
    'auth.avatar.ring': 'Rings',
    'auth.avatar.bauhaus': 'Bauhaus',
    // 404
    'notfound.title': 'Page not found',
    'notfound.desc': 'The page you are looking for does not exist or has moved. Let us get back on track.',
    'notfound.home': 'Go home',
    // Footer
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.contact': 'Contact',
    'footer.copy': 'Made with AI for students.',
    // Auth - email confirmation
    'auth.checkmail': 'Check your email',
    'auth.checkmail.desc': 'We sent a confirmation link to',
    'auth.checkmail.resend': 'Resend email',
    'auth.checkmail.resending': 'Sending...',
    'auth.checkmail.sent': 'Email resent!',
    'auth.checkmail.open': 'Open email',
    'auth.checkmail.note': 'Click the link to activate your account. Your session will start automatically.',
    'auth.confirmed': 'Account confirmed!',
    'auth.confirmed.desc': 'Your session has started automatically.',
    'auth.confirm.error': 'We could not confirm the account. The link may have expired.',
    'auth.backto.login': 'Back to login',
    // Profile / dropdown
    'profile.menu': 'My account',
    'profile.sessions': 'My sessions',
    'profile.recentsessions': 'Recent sessions',
    'profile.settings': 'Settings',
    'profile.logout': 'Log out',
    'profile.free': 'Free',
    'profile.xp': 'XP',
    'profile.streak': 'Streak',
    'profile.days': 'days',
    'profile.nosessions': 'You have no saved sessions yet',
    'profile.opensession': 'Open session',
    'profile.back': 'Back',
    // Library (folders / storage)
    'library.title': 'My Library',
    'library.subtitle': 'Organize your decks into folders. Drag a deck onto a folder to move it.',
    'library.filter': 'Filter decks...',
    'library.newfolder': 'New folder',
    'library.foldername': 'Folder name',
    'library.uncategorized': 'Uncategorized',
    'library.all': 'All decks',
    'library.rename': 'Rename',
    'library.delete': 'Delete',
    'library.move': 'Move to...',
    'library.moved.to': 'Moved to {folder}',
    'library.study': 'Study',
    'library.empty': 'You have no saved decks yet.',
    'library.folder.empty': 'This folder is empty.',
    'library.confirm.delete.folder': 'Delete this folder? Its decks will move back to "Uncategorized".',
    'library.confirm.delete.session': 'Delete this deck? This cannot be undone.',
    'library.rename.session': 'Rename deck',
    'library.session.name': 'Deck name',
    'library.cards': 'cards',
    'library.open': 'Open',
    'library.color': 'Color',
    'library.color.none': 'No color',
    'library.export.csv': 'Export CSV',
    'library.newfolder.here': 'New folder',
    'library.created': 'Folder created',
    'library.renamed': 'Folder renamed',
    'library.save': 'Save',
    'library.last': 'Last time',
    'library.never': 'Not studied',
    'library.style': 'Style',
    'library.move.short': 'Move',
    'library.delete.withcontents': 'Delete with contents',
    'library.confirm.delete.folder.plain': 'Delete this folder? Its contents will stay in this same place.',
    'library.confirm.delete.folder.contents': 'Permanently delete this folder AND all its contents? This cannot be undone.',
    // Rewards
    'reward.title': 'Session complete!',
    'reward.subtitle': 'You reviewed',
    'reward.cards': 'cards',
    'reward.known': 'mastered',
    'reward.time': 'Time',
    'reward.accuracy': 'Accuracy',
    'reward.xp': '+{amount} XP earned',
    'reward.xp.already': 'XP already earned',
    'reward.save.title': 'Save this deck',
    'reward.save.cta': 'Save',
    'reward.save.folder': 'Folder',
    'reward.saved': 'Deck saved to your library',
    'reward.discard': 'Discard',
    'reward.discarded': 'Deck discarded',
    'reward.discard.warn': 'The current deck will be discarded and not saved. Continue?',
    'reward.upload.another': 'Upload another file',
    'reward.streak': '{days}-day streak!',
    'reward.streak.best': 'Your best streak',
    'reward.review': 'Review again',
    'reward.home': 'Back home',
    'reward.level': 'Level {level}',
    'reward.correct.list': 'Got it',
    'reward.wrong.list': 'Missed',
    'reward.show.wrong': 'See what I missed',
    'reward.hide.wrong': 'Hide',
    'reward.retry.wrong': 'Review only the missed ones',
    'reward.finish': 'Finish session',
    'reward.summary': 'Session summary',
    'reward.unanswered': 'Unanswered: {count}',
    'study.end': 'Finish',
    'study.review.wrong': 'Review missed',
    'study.unanswered.warn': '{count} still unanswered',
    'export.title': 'Export sessions',
    'export.desc': 'Download all your flashcards to use anywhere.',
    'export.csv': 'Export CSV',
    'export.json': 'Export JSON',
    'export.single': 'Export this deck',
    'export.done': 'Sessions exported',
    'export.one': 'Deck exported',
    'filename.label': 'File name (optional)',
    'filename.placeholder': 'e.g. Topic 3 - Photosynthesis',
    'cta.bottom': 'Ready to start? Create your flashcards',
    'cta.create': 'Create my flashcards',
    // Chatbot
    'chatbot.title': 'Mara · Assistant',
    'chatbot.placeholder': 'Type or tap a suggestion...',
    'chatbot.welcome': 'Hi! I\'m Mara, your StudySpark assistant 😊 Are you about to build a new deck or reviewing one? I\'m here for whatever you need.',
    'chatbot.help': 'Online and happy to help',
    'chatbot.back': 'Back to topics',
    'chatbot.unknown': 'Hmm, that one\'s a bit outside my wheelhouse 🤔 Try asking me about: creating cards, study modes, exporting your decks, your account, or how to support us. Where would you like to start?',
    'chatbot.topics.create': 'Great choice! Go to Home, paste your notes or upload a file (PDF, TXT or DOCX) and hit "Generate". In seconds the AI turns your notes into questions and answers, and even tags each card with its difficulty. Once they\'re ready, pick how you want to review and you\'re off! 🚀',
    'chatbot.topics.study': 'We have 3 modes for every taste: Basic (your pace, no rush), Timed (a fixed 30s per card, trains you to think fast) and Spaced Repetition (the AI repeats each card just before you\'d forget it). Pick them in the settings button ⚙️ before you start. Which would you like to try?',
    'chatbot.topics.export': 'Of course. When you finish a session you\'ll see buttons to export to CSV or JSON, and from Settings > My Data you can grab all your sessions at once. Your cards travel with you wherever you like. 📤',
    'chatbot.topics.account': 'Create your account with your email and your progress, streak and points are saved automatically. Open it on any device and everything is right where you left it. 🔐',
    'chatbot.topics.donate': 'StudySpark is free and open source, and I want it to stay that way forever ☕ If it helps you and you\'d like to buy me a coffee, here\'s my Ko-fi: https://ko-fi.com/mvalera_dev. But heads up: it\'s never required, every mode is free regardless. Thank you from the bottom of my heart! ❤️',
    // Upload area
    'upload.title': 'Upload your notes',
    'upload.cardcount.note': 'default',
    'upload.cardcount.auto': 'Let the AI decide',
    'upload.drag': 'Drag and drop your file',
    'upload.click': 'or click to browse',
    'upload.formats': 'PDF, TXT, DOCX (max 10MB)',
    'upload.drop': 'Drop the file here',
    'upload.text.label': 'Paste your notes directly:',
    'upload.text.placeholder': 'Paste your notes text here...',
    'upload.or': 'OR',
    'upload.clear': 'Clear',
    'upload.fromtext': 'Generate from text',
    'upload.fromfile': 'Generate from file',
    'upload.processing': 'Processing your notes...',
    'upload.processing.sub': 'The AI is creating your flashcards',
    // Loading screen (async generation)
    'loading.title': 'Generating your flashcards',
    'loading.step.reading': 'Reading your document...',
    'loading.step.thinking': 'The AI is studying the content...',
    'loading.step.writing': 'Writing the flashcards...',
    'loading.step.almost': 'Almost there, adding the final touches...',
    'loading.hint': 'This can take up to a couple of minutes. Please keep this page open.',
    'loading.timeout': 'Generation is taking too long. Please try again.',
    'upload.preview': 'Preview:',
    // Flashcard
    'card.question': 'Question',
    'card.answer': 'Answer',
    'card.copy': 'Copy',
    'card.copied': 'Copied!',
    'card.listen': 'Listen',
    'card.stop': 'Stop',
    'card.flip.hint.short': 'Tap the card to flip',
    'card.very-easy': 'Very easy',
    'card.easy': 'Easy',
    'card.medium': 'Medium',
    'card.hard': 'Hard',
    'card.very-hard': 'Very hard',
    'card.no.difficulty': 'No level',
    'card.time.up': "Time's up!",
    // Study modes
    'mode.basic': 'Basic',
    'mode.timed': 'Timed',
    'mode.spaced': 'Spaced repetition',
    'mode.basic.desc': 'Study at your own pace, no rush.',
    'mode.timed.desc': 'Answer before the time runs out.',
    'mode.spaced.desc': 'The AI repeats each card just before you forget it.',
    'mode.recording': 'Recording',
    'mode.paused': 'Paused',
    // Session config
    'config.title': 'Set up your session',
    'config.subtitle': 'Choose how you want to review this deck.',
    'config.mode': 'Study mode',
    'config.order': 'Card order',
    'config.order.default': 'As-is (original order)',
    'config.order.shuffle': 'Shuffle randomly',
    'config.order.hard': 'Hardest first',
    'config.direction': 'Direction',
    'config.direction.qa': 'Question → Answer',
    'config.direction.aq': 'Answer → Question',
    'config.autoplay': 'Read aloud when flipping',
    'config.start': 'Start studying',
    'config.cancel': 'Cancel',
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your study experience.',
    'settings.language': 'Language',
    'settings.lang.es': 'Spanish',
    'settings.lang.en': 'English',
    'settings.studyprefs': 'Study preferences',
    'settings.defaultmode': 'Default mode',
    'settings.cardcount': 'Flashcards per deck',
    'settings.cardcount.max': 'max',
    'settings.speak': 'Read cards aloud',
    'settings.speak.desc': 'Plays the text automatically when flipping each card.',
    'settings.autoplay': 'Auto-play',
    'settings.autoplay.desc': 'Turn on voice reading by default in new sessions.',
    'settings.data': 'My data',
    'settings.export': 'Export my sessions',
    'settings.export.desc': 'Download all your flashcards as CSV to use anywhere.',
    'settings.delete': 'Delete my progress',
    'settings.delete.desc': 'Remove saved sessions from this device.',
    'settings.delete.confirm': 'Delete all local progress? This cannot be undone.',
    'settings.deleted': 'Progress deleted',
    'settings.saved': 'Preferences saved',
    'settings.account': 'Account',
    'settings.plan': 'Plan',
    'settings.avatar': 'Your avatar',
    'settings.avatar.desc': 'Geometric profile avatar',
    'settings.avatar.saved': 'Avatar updated',
    // FAQ
    'faq.search': 'Search the questions...',
    'faq.noresults': 'No questions found for your search.',
    'faq.cat.all': 'All',
    'faq.cat.general': 'General',
    'faq.cat.files': 'Files & formats',
    'faq.cat.study': 'Study & modes',
    'faq.help.title': 'Still have questions?',
    'faq.help.desc': 'Write to us and we will help within 24h.',
    'faq.help.button': 'Contact',
    'faq.q6': 'Can I use StudySpark on mobile?',
    'faq.a6': 'Yes. StudySpark is a responsive web app: it adapts to your phone and tablet without installing anything. You only need a browser.',
    'faq.q7': 'What is timed mode?',
    'faq.a7': 'Each card has 30 seconds to answer. It trains you to think fast under pressure.',
    'faq.q8': 'Can I export my cards?',
    'faq.a8': 'Yes, when you finish a session you\'ll see buttons to export to CSV or JSON. Also from Settings > My Data.',
    'faq.q9': 'What happens if I lose my streak?',
    'faq.a9': 'If you skip a day, the streak resets to 1. But you can rebuild it by studying the next day. Your accumulated XP stays!',
    'faq.q10': 'How do I contact you?',
    'faq.a10': 'Use the contact button in the header or write to hola@studyspark.pp.ua. We reply within 24h.',
    'faq.cat.support': 'Support',
    // Nav
    'nav.ajustes': 'Settings',
    // Contact page
    'contact.title': 'Contact us',
    'contact.subtitle': 'Have questions, suggestions, or just want to say hi? Write to us and we will reply within 24h.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send',
    'contact.sending': 'Sending...',
    'contact.sent': 'Message sent!',
    'contact.success.title': 'Message sent!',
    'contact.success.desc': 'Thanks for contacting us. We will get back to you as soon as possible.',
    'contact.another': 'Send another message',
    'contact.home': 'Back to home',
    'contact.privacy': 'By submitting you agree to our privacy policy.',
  },
} as const

type Lang = keyof typeof translations
type Dict = (typeof translations)[Lang]

interface LanguageContextValue {
  lang: Lang
  t: (key: keyof Dict, vars?: Record<string, string | number>) => string
  toggle: () => void
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

const LANG_STORAGE_KEY = 'studyspark.lang'

// Read the persisted language once, falling back to Spanish.
function loadLang(): Lang {
  try {
    const saved = localStorage.getItem(LANG_STORAGE_KEY)
    if (saved === 'es' || saved === 'en') return saved
  } catch {
    /* ignore */
  }
  return 'es'
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>(loadLang)

  // Persist the language so it survives reloads and new sessions.
  useEffect(() => {
    try {
      localStorage.setItem(LANG_STORAGE_KEY, lang)
    } catch {
      /* ignore */
    }
  }, [lang])

  const toggle = useCallback(() => {
    setLang((l) => (l === 'es' ? 'en' : 'es'))
  }, [])

  const t = useCallback(
    (key: keyof Dict, vars?: Record<string, string | number>): string => {
      let str = (translations[lang][key] as string) ?? String(key)
      if (vars) {
        for (const [k, v] of Object.entries(vars)) {
          str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v))
        }
      }
      return str
    },
    [lang]
  )

  return (
    <LanguageContext.Provider value={{ lang, t, toggle }}>{children}</LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}